### ISSUE TITLE
Websocket requests fail

### ISSUE THREAD

**Issue by mmoutenot** [rain0r/ampd#10]
I hope this isn't too one-off. If it is feel free to close the issue.

When running the ampd, I notice a series of websocket requests attempting to connect to mpd that fail. mpd is running (`bind_to_address "localhost"`, `port "6600"`) and other clients are connected.

When I crank up the log levels, I see the following WARN

```
2020-05-31 10:06:32.021  WARN 58291 --- [essageBroker-16] org.bff.javampd.server.MPDServerStatus   : Response did not contain status error:
2020-05-31 10:06:32.022  WARN 58291 --- [essageBroker-16] org.bff.javampd.server.MPDServerStatus   : Response did not contain status updating_db:
```

Upon boot there are a couple of warnings but nothing that I think is related.

I'll take a look at the code to see where the above warnings are dispatched, but posting here in case anyone has run into this before.

Looks like a cool project! Thanks.

**Comment by rain0r** [comment]
Hey there, 

the issue lies in the dependency [`javampd`](https://github.com/finnyb/javampd), or rather in my [fork](https://github.com/rain0r/javampd) of it. I forked it because it seems orphaned and I wanted to add `consume` and `single` as playback options.

So these messages occur every time [`getServerStatus()`](https://github.com/rain0r/javampd/blob/develop/src/main/java/org/bff/javampd/server/MPD.java#L192) is called, and since it's getting called every second by the [`ScheduledStatePublisher`](https://github.com/rain0r/ampd/blob/master/src/main/java/org/hihn/ampd/server/sender/ScheduledStatePublisher.java), it procudes *a lot* of log messages. That's why I turned logging off for this class in the `application.properties`.

As for the why, I just can't answer that. Actually I looked at it again but all I can say is that it hasn't got anything to do with `ampd`.

For example, I just set a breakpoint in the method `getXFade()` which is identified in the response with `xfade`. This is the response from the server (as array):

```
0 = "volume: 4"
1 = "repeat: 0"
2 = "random: 1"
3 = "single: 0"
4 = "consume: 0"
5 = "playlist: 24"
6 = "playlistlength: 18"
7 = "mixrampdb: 0.000000"
8 = "state: pause"
9 = "song: 9"
10 = "songid: 153"
11 = "time: 136:284"
12 = "elapsed: 135.938"
13 = "bitrate: 904"
14 = "duration: 283.853"
15 = "audio: 44100:16:2"
16 = "nextsong: 4"
17 = "nextsongid: 146" 
```

`xfade` is missing and so the warning is logged.

But actually, according to the [mpd protocol](https://www.musicpd.org/doc/html/protocol.html#command-reference), `status` should include `xfade`.

Quite interesting, although I think I'm just missing something.

Anyway, hope I could tell you something new and thanks for kind words!

**Comment by mmoutenot** [comment]
Thanks for the thoughtful response!

I'll try to dig in a bit more to see if I can come up with a workaround or identify a misconfiguration on my part.

I'll close for now and add information I find that might be helpful to others in the future.
