### ISSUE TITLE
Proposal: Hide volume slider, if volume isn't available (output shout)

### ISSUE THREAD

**Issue by nowrap** [rain0r/ampd#12]
Hello,
the angular client shows a -1 % and the ampd service throws an exception if trying to change:
> 2020-06-05 18:07:30.590 ERROR 2368 --- [boundChannel-25] o.h.a.s.controller.WebSocketController   : [52@0] {setvol} problems setting volume
> 
> org.bff.javampd.server.MPDConnectionException: [52@0] {setvol} problems setting volume

Maybe hiding or deactivating the volume slider is an option if changing the volume isn't available?

Regards
nowrap

**Comment by rain0r** [comment]
Hi there,
this one is difficult for me to reproduce. Do you have any more info why the volume is at -1%? Does this also happen when you're using another MPD client? 

Anyway, I followed your advice, the volume slider is now hidden on a negative value (the same applies for the progress bar). Fixed in: 5651f748128d74d9edd608f9fa418e54a3003903

Are you building ampd yourself or do you need a new release?

**Comment by rain0r** [comment]
I'm closing this ticket, the issue should be resolved.
